# Node.js action to upload junit test result files to Datadog Test Optimization
name: "Datadog JUnitXML Upload"
description: "Upload JUnitXML reports files to Datadog Test Optimization"
inputs:
  api_key:
    required: true
    description: Datadog API key to use to upload the junit files.
  site:
    required: false
    default: datadoghq.com
    description: The Datadog site to upload the files to.
  files:
    required: true
    description: JUnit files to upload.
    default: .
  auto-discovery:
    required: true
    description: Do a recursive search and automatic junit files discovery in the folders provided in `files` input (current folder if omitted).
    default: 'true'
  ignored-paths:
    required: false
    description: A comma-separated list of paths that are ignored when junit files auto-discovery is done. Glob patterns are supported
  concurrency:
    required: true
    description: Controls the maximum number of concurrent file uploads.
    default: "20"
  tags:
    required: false
    description: Datadog tags to associate with the uploaded test results.
  service:
    required: false
    description: Service name to use with the uploaded test results.
  env:
    required: false
    description: Datadog env to use for the tests.
  logs:
    required: false
    description: Set to "true" to enable forwarding content from XML reports as logs.
  extra-args:
    default: ""
    description: Extra args to be passed to the datadog-ci cli.
    required: false
runs:
  using: node24
  main: dist/index.js
