name: 'Test Action'
on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          api-key: ${{secrets.DD_API_KEY}}
          datadog-site: datad0g.com
          logs: "true"
          files: ./ci/fixtures/
          service: junit-upload-github-action
          env: ci
          tags: "foo:bar,alpha:bravo"
      - name: Tag pipeline with ci version
        run: |
          datadog-ci tag --level pipeline --tags "datadogci.version:`npm list -g @datadog/datadog-ci | grep @datadog/datadog-ci | awk -F' ' '{print $2}' | awk -F'@' '{print $3}' | tr -d '\n'`"
        env:
          DATADOG_API_KEY: ${{secrets.DD_API_KEY}}
          DATADOG_SITE: datad0g.com