name: 'Test Action'
on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'
      - juan-fernandez/testing-new-version
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  test-glob-pattern:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload reports using a glob pattern
        uses: ./
        with:
          api-key: ${{secrets.DD_API_KEY_CI_VISIBILITY}}
          logs: "true"
          files: '**/fixtures/**'
          service: junit-upload-github-action-tests
          env: ci
          tags: "foo:bar,alpha:bravo"
      - name: Check that test data can be queried
        run: |
          npm install @datadog/datadog-api-client
          node ./check-junit-upload.js
        env:
          EXTRA_TAGS: "@foo:bar @alpha:bravo"
          DD_API_KEY: ${{ secrets.DD_API_KEY_CI_VISIBILITY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY_CI_VISIBILITY }}
          DD_SERVICE: junit-upload-github-action-tests